development:
 adapter: sqlite3
 database: db/development.sqlite3
 pool: 5
 timeout: 5000

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: wtbdev
#   pool: 5
#   timeout: 5000
#   password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  encoding: unicode
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
  password:
